[versions]
kotlin = "2.1.0"
dokka = "1.9.20"
ksp = "2.1.0-1.0.29"
poet = "2.0.0"

[libraries]
symbol-processing = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-poet = { module = "com.squareup:kotlinpoet", version.ref = "poet" }
kotlin-poet-ksp = { module = "com.squareup:kotlinpoet-ksp", version.ref = "poet" }

# actual plugins, but needed as dependencies in buildSrc
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
dokka-gradle-plugin = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }
serialization-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }

[plugins]
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

[bundles]
build-src = [
    "kotlin-gradle-plugin",
    "dokka-gradle-plugin",
    "serialization-gradle-plugin"
]